""" Vundle settings

set shell=/bin/bash "required if using another shell
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'airblade/vim-gitgutter'
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/rainbow_parentheses.vim' " Colorful parentheses
Plugin 'Lokaltog/vim-easymotion'      " Improved motion
Plugin 'mhinz/vim-signify'
Plugin 'scrooloose/syntastic'         " Syntax highlighting
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'tpope/vim-fugitive'           " Git integration
Plugin 'vim-scripts/fish-syntax'

" Haskell
Plugin 'eagletmt/ghcmod-vim'          " Load buffer in ghc, infer types
Plugin 'eagletmt/neco-ghc'            " Auto completion
Plugin 'bitc/vim-hdevtools'           " Provide type information
Plugin 'vim-scripts/Haskell-Conceal'  " Replace characters with unicode equivalents
Plugin 'wlangstroth/vim-haskell'      " syntax highlighting

" Javascript
Plugin 'jelera/vim-javascript-syntax'     " Syntax highlighting
Plugin 'nathanaelkane/vim-indent-guides'  " Show indent guides
Plugin 'pangloss/vim-javascript'          " Highlighting + better indentation
Plugin 'walm/jshint.vim'                  " Hints

" Purescript
Plugin 'raichoo/purescript-vim'

call vundle#end()
filetype plugin indent on

""" General settings

syntax on                   " Enable syntax highlighting
set number                  " Enable line numbers
set autoread                " Refresh buffers if they were changed from outside
set autowriteall            " Save on buffer switch
set splitright              " Split new buffers to the right

set directory=~/.vim/tmp    " Temporary swap files directory

set hlsearch                " Highlight search matches
set nolist                  " Do not highlight whitespaces by default
set listchars=tab:▸\ ,eol:¬ " Display tabs as ▸, end of line as `¬`

set guioptions+=a           " Copy highlighted text to system clipboard
set guioptions-=r           " Remove scrollbars
set guioptions-=L

colorscheme desert          " Color scheme

" Soft tab indentation with 2 spaces
set tabstop=2
set shiftwidth=2

set smarttab
set expandtab               " Use spaces instead of tabs

set laststatus=2            " Always show status bar

""" Syntastic
let g:syntastic_auto_loc_list=1

""" Unite settings
let g:unite_source_history_yank_enable = 1
call unite#custom#source('file,file/new,buffer,file_rec,file_rec/async', 'matchers', 'matcher_fuzzy')
call unite#custom#source('file,file/new,buffer,file_rec,file_rec/async', 'sorters', 'sorter_rank')

call unite#custom#source('file,file_rec,file_rec/async', 'ignore_pattern',
      \'tmp\|vendor\|\.bundle\|target\|\.git')

""" Mappings

" go back to Normal Mode
inoremap jk <Esc>
" split line
inoremap <leader>c <CR><Esc>O
nnoremap <leader>c <CR><Esc>O

" Toggle whitespaces/end of line display
nnoremap <leader>l :set list!<CR>

" Unite
nnoremap <C-p> :Unite -no-split -buffer-name=files -start-insert file_rec/async:!<cr>

" Buffer navigation
nnoremap be :enew<CR>
nnoremap bl :bnext<CR>
nnoremap bh :bprevious<CR>
nnoremap bq :bdelete<CR>

""" syntastic
map <silent> <leader>e :Errors<CR>
map <Leader>s :SyntasticToggleMode<CR>

""" ghc-mod
nnoremap <silent> gb :GhcModCheck<CR>
nnoremap <silent> gt :GhcModType<CR>
nnoremap <silent> gc :GhcModTypeClear<CR>
nnoremap <silent> gn :GhcModLint<CR>
nnoremap <silent> ge :GhcModExpand<CR>

""" rainbow-parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]

" let g:rbpt_max = 16
" let g:rbpt_loadcmd_toggle = 0

" Remove trailing whitespaces on save
autocmd BufWritePre *.* :%s/\s\+$//e

