""" Vundle settings

set shell=/bin/bash                       "required if using another shell
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'                " Plugin manager
Plugin 'kien/rainbow_parentheses.vim'     " Colorful parentheses
Plugin 'Lokaltog/vim-easymotion'          " Improved motion
Plugin 'scrooloose/syntastic'             " Syntax highlighting
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimproc.vim'               " Required by unite.vim
Plugin 'tpope/vim-surround'               " Surround words
Plugin 'tpope/vim-vinegar'                " Improved file explorer

" Color scheme
Plugin 'nanotech/jellybeans.vim'

" Git integration
Plugin 'airblade/vim-gitgutter'           " Git info in gutter
Plugin 'tpope/vim-fugitive'               " Git integration

" Haskell
Plugin 'bitc/vim-hdevtools'               " Provide type information
Plugin 'eagletmt/ghcmod-vim'              " Load buffer in ghc, infer types
Plugin 'eagletmt/neco-ghc'                " Auto completion
Plugin 'vim-scripts/Haskell-Conceal'      " Replace characters with unicode equivalents
Plugin 'wlangstroth/vim-haskell'          " syntax highlighting

" Javascript
Plugin 'jelera/vim-javascript-syntax'     " Syntax highlighting
Plugin 'nathanaelkane/vim-indent-guides'  " Show indent guides
Plugin 'pangloss/vim-javascript'          " Highlighting + better indentation
Plugin 'walm/jshint.vim'                  " Hints

" Angular
Plugin 'burnettk/vim-angular'

" SASS
Plugin 'tpope/vim-haml'

" Fish
Plugin 'vim-scripts/fish-syntax'

call vundle#end()
filetype plugin indent on

""" General settings

syntax on                   " Enable syntax highlighting
set t_Co=256                " Set terminal colours
set number                  " Enable line numbers
set autoread                " Refresh buffers if they were changed from outside
set autowriteall            " Save on buffer switch
set splitright              " Split new buffers to the right
set mouse=a                 " Enable mouse
set encoding=utf8
set guifont=Source\ Code\ Pro\ for\ Powerline:h14

set nocursorline            " Don't paint cursor line (scrolling becomes painfully slow)
set nocursorcolumn          " Don't paint cursor column (scrolling becomes painfully slow)
set lazyredraw              " Wait to redraw

set hlsearch                " Highlight search matches
set incsearch               " Highlight search matches as you type

set ignorecase              " Ignore case when searching
set smartcase               " Ignore case if pattern is lowercase, case-sensitive otherwise

set nobackup                " Disable backup
set directory=~/.vim/tmp    " Temporary swap files directory

set nolist                  " Do not highlight whitespaces by default
set listchars=tab:▸\ ,eol:¬ " Display tabs as ▸, end of line as `¬`

set guioptions+=a           " Copy highlighted text to system clipboard
set guioptions-=r           " Remove scrollbars
set guioptions-=L

set noshowmode              " Hide the default mode text

colorscheme jellybeans      " Set default color scheme

set tabstop=2               " Soft tab indentation with 2 spaces
set shiftwidth=2

set smarttab
set expandtab               " Use spaces instead of tabs

set laststatus=2            " Always show status bar

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set guitablabel=%M\ %t
endif

""" Syntastic
let g:syntastic_auto_loc_list=1

""" Unite
let g:unite_source_history_yank_enable = 1
call unite#custom#source('file,file/new,buffer,file_rec,file_rec/async', 'matchers', 'matcher_fuzzy')
call unite#custom#source('file,file/new,buffer,file_rec,file_rec/async', 'sorters', 'sorter_rank')

call unite#custom#source('file,file_rec,file_rec/async', 'ignore_pattern',
      \'tmp\|vendor\|\.bundle\|target\|\.git')

""" Mappings

" Remap leader to backtick
let mapleader="`"

" Quickly edit and source ~/.vimrc
nmap <silent> <leader>ev :tabnew $MYVIMRC<CR>
nmap <silent> <leader>es :so $MYVIMRC<CR>

" Use ; to write commands, insteaf of :
nnoremap ; :

" go back to Normal Mode
inoremap jk <Esc>

" clear search highlightings
nmap <silent> `` :nohlsearch<CR>

" split line
inoremap <leader>c <CR><Esc>O
nnoremap <leader>c <CR><Esc>O

" toggle whitespaces/end of line display
nnoremap <leader>l :set list!<CR>

" resize split panes with arrows
if bufwinnr(1)
  nmap <Up> <C-w>+
  nmap <Down> <C-w>-
  nmap <Right> <C-w>>
  nmap <Left> <C-w><
endif

" unite
nnoremap <C-p> :Unite -no-split -buffer-name=files -start-insert file_rec/async:!<cr>

" Buffer navigation
" nnoremap be :enew<CR>
" nnoremap bl :bnext<CR>
" nnoremap bh :bprevious<CR>
" nnoremap bq :bdelete<CR>

" syntastic
map <silent> <leader>e :Errors<CR>
map <leader>s :SyntasticToggleMode<CR>

" ghc-mod
" nnoremap <silent> gb :GhcModCheck<CR>
" nnoremap <silent> gt :GhcModType<CR>
" nnoremap <silent> gc :GhcModTypeClear<CR>
" nnoremap <silent> gn :GhcModLint<CR>
" nnoremap <silent> ge :GhcModExpand<CR>

""" rainbow-parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]

" Remove trailing whitespaces on save
autocmd BufWritePre *.* :%s/\s\+$//e

" Powerline integration
source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim

" Provide autocompletion options for tags in css, html files
" (triggered with <C-x><C-o>)
autocmd FileType css set omnifunc=htmlcomplete#CompleteTags
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags

